package com.fabianachammer.procgenf.generation;

import java.util.Set;

/**
 * Represents a part of the world to be generated that is only readable.
 * 
 * @author fachammer
 *
 */
public interface ReadableChunk {

	/**
	 * @return The parent of the chunk or null, if it is the root element.
	 */
	ReadableChunk getParent();

	/**
	 * @return The siblings of this chunk or the empty set, if the chunk has no
	 *         siblings.
	 */
	Set<ReadableChunk> getSiblings();

	/**
	 * @return All children of this chunk.
	 */
	Set<ReadableChunk> getChildren();

	/**
	 * @return Number of ancestors for this chunk
	 */
	int getDepth();

	/**
	 * @return set of chunk features ordered by insertion order
	 */
	Set<ChunkFeature> getFeatures();

	/**
	 * @return true, if the chunk was generated by a generation engine, false,
	 *         if the chunk was degenerated or is not yet generated
	 */
	boolean isGenerated();
}
